import puppeteer, { Browser } from 'puppeteer';

let browserInstance: Browser | null = null;

async function getBrowser(): Promise<Browser> {
  if (!browserInstance || !browserInstance.connected) {
    browserInstance = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
    });
  }
  return browserInstance;
}

export interface PDFGenerationOptions {
  title: string;
  subtitle?: string;
  organisationName: string;
  generatedAt?: Date;
  orientation?: 'portrait' | 'landscape';
}

export async function generatePDFFromHTML(
  htmlContent: string,
  options: PDFGenerationOptions
): Promise<Buffer> {
  const browser = await getBrowser();
  const page = await browser.newPage();

  const fullHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          font-size: 11px;
          line-height: 1.4;
          color: #1a1a1a;
          padding: 20px;
        }
        .header {
          text-align: center;
          margin-bottom: 24px;
          padding-bottom: 16px;
          border-bottom: 2px solid #333;
        }
        .header h1 {
          font-size: 18px;
          font-weight: 700;
          margin-bottom: 4px;
        }
        .header h2 {
          font-size: 14px;
          font-weight: 600;
          color: #555;
        }
        .header .subtitle {
          font-size: 12px;
          color: #666;
          margin-top: 4px;
        }
        .header .date {
          font-size: 10px;
          color: #888;
          margin-top: 8px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 16px;
        }
        th, td {
          padding: 8px 10px;
          text-align: left;
          border-bottom: 1px solid #ddd;
        }
        th {
          background-color: #f5f5f5;
          font-weight: 600;
          font-size: 10px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          color: #555;
        }
        tr:nth-child(even) {
          background-color: #fafafa;
        }
        .text-right {
          text-align: right;
        }
        .text-center {
          text-align: center;
        }
        .font-bold {
          font-weight: 600;
        }
        .total-row {
          font-weight: 700;
          background-color: #f0f0f0 !important;
          border-top: 2px solid #333;
        }
        .section-header {
          background-color: #e8e8e8;
          font-weight: 600;
        }
        .indent {
          padding-left: 24px;
        }
        .footer {
          margin-top: 32px;
          padding-top: 16px;
          border-top: 1px solid #ddd;
          font-size: 9px;
          color: #888;
          text-align: center;
        }
        .summary-box {
          background: #f9f9f9;
          border: 1px solid #ddd;
          border-radius: 4px;
          padding: 16px;
          margin: 16px 0;
        }
        .summary-row {
          display: flex;
          justify-content: space-between;
          padding: 4px 0;
        }
        .negative {
          color: #dc2626;
        }
        .positive {
          color: #16a34a;
        }
        @page {
          margin: 15mm;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${options.organisationName}</h1>
        <h2>${options.title}</h2>
        ${options.subtitle ? `<div class="subtitle">${options.subtitle}</div>` : ''}
        <div class="date">Generated: ${(options.generatedAt || new Date()).toLocaleString()}</div>
      </div>
      ${htmlContent}
      <div class="footer">
        This report was generated by IPSAS Accounting System. Confidential - for authorized use only.
      </div>
    </body>
    </html>
  `;

  await page.setContent(fullHtml, { waitUntil: 'networkidle0' });

  const pdfBuffer = await page.pdf({
    format: 'A4',
    landscape: options.orientation === 'landscape',
    printBackground: true,
    margin: {
      top: '10mm',
      right: '10mm',
      bottom: '10mm',
      left: '10mm',
    },
  });

  await page.close();

  return Buffer.from(pdfBuffer);
}

export function formatCurrency(amount: number | string | null | undefined, decimals = 2): string {
  const num = typeof amount === 'string' ? parseFloat(amount) : (amount || 0);
  return num.toLocaleString('en-US', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

export function generateTrialBalanceHTML(data: any): string {
  let html = `
    <table>
      <thead>
        <tr>
          <th>Account Code</th>
          <th>Account Name</th>
          <th class="text-right">Debit</th>
          <th class="text-right">Credit</th>
        </tr>
      </thead>
      <tbody>
  `;

  for (const row of data.accounts || []) {
    html += `
      <tr>
        <td>${row.code}</td>
        <td>${row.name}</td>
        <td class="text-right">${row.debit ? formatCurrency(row.debit) : ''}</td>
        <td class="text-right">${row.credit ? formatCurrency(row.credit) : ''}</td>
      </tr>
    `;
  }

  html += `
      <tr class="total-row">
        <td colspan="2">TOTALS</td>
        <td class="text-right">${formatCurrency(data.totalDebit)}</td>
        <td class="text-right">${formatCurrency(data.totalCredit)}</td>
      </tr>
    </tbody>
    </table>
  `;

  return html;
}

export function generateGeneralLedgerHTML(data: any): string {
  let html = '';

  for (const account of data.accounts || []) {
    html += `
      <div style="margin-bottom: 24px; page-break-inside: avoid;">
        <h3 style="font-size: 12px; margin-bottom: 8px; padding: 8px; background: #f0f0f0;">
          ${account.code} - ${account.name}
        </h3>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Reference</th>
              <th>Description</th>
              <th class="text-right">Debit</th>
              <th class="text-right">Credit</th>
              <th class="text-right">Balance</th>
            </tr>
          </thead>
          <tbody>
    `;

    for (const entry of account.entries || []) {
      html += `
        <tr>
          <td>${new Date(entry.date).toLocaleDateString()}</td>
          <td>${entry.reference || ''}</td>
          <td>${entry.description}</td>
          <td class="text-right">${entry.debit ? formatCurrency(entry.debit) : ''}</td>
          <td class="text-right">${entry.credit ? formatCurrency(entry.credit) : ''}</td>
          <td class="text-right">${formatCurrency(entry.balance)}</td>
        </tr>
      `;
    }

    html += `
          </tbody>
        </table>
      </div>
    `;
  }

  return html;
}

export function generateFinancialPositionHTML(data: any): string {
  let html = '<table><tbody>';

  const renderSection = (title: string, items: any[], isLiability = false) => {
    let sectionTotal = 0;
    let sectionHtml = `<tr class="section-header"><td colspan="2">${title}</td></tr>`;

    for (const item of items) {
      const amount = parseFloat(item.balance || 0);
      sectionTotal += amount;
      sectionHtml += `
        <tr>
          <td class="indent">${item.code} - ${item.name}</td>
          <td class="text-right">${formatCurrency(Math.abs(amount))}</td>
        </tr>
      `;
    }

    sectionHtml += `
      <tr class="font-bold">
        <td>Total ${title}</td>
        <td class="text-right">${formatCurrency(Math.abs(sectionTotal))}</td>
      </tr>
    `;

    return { html: sectionHtml, total: sectionTotal };
  };

  const assets = renderSection('ASSETS', data.assets || []);
  const liabilities = renderSection('LIABILITIES', data.liabilities || [], true);
  const netAssets = renderSection('NET ASSETS / EQUITY', data.netAssets || []);

  html += assets.html;
  html += '<tr><td colspan="2" style="height: 16px;"></td></tr>';
  html += liabilities.html;
  html += '<tr><td colspan="2" style="height: 16px;"></td></tr>';
  html += netAssets.html;

  html += `
    <tr class="total-row">
      <td>TOTAL LIABILITIES AND NET ASSETS</td>
      <td class="text-right">${formatCurrency(Math.abs(data.totalLiabilitiesAndNetAssets || 0))}</td>
    </tr>
  `;

  html += '</tbody></table>';
  return html;
}

export function generateFinancialPerformanceHTML(data: any): string {
  let html = '<table><tbody>';

  const renderSection = (title: string, items: any[]) => {
    let sectionTotal = 0;
    let sectionHtml = `<tr class="section-header"><td colspan="2">${title}</td></tr>`;

    for (const item of items) {
      const amount = parseFloat(item.balance || 0);
      sectionTotal += amount;
      sectionHtml += `
        <tr>
          <td class="indent">${item.code} - ${item.name}</td>
          <td class="text-right">${formatCurrency(Math.abs(amount))}</td>
        </tr>
      `;
    }

    sectionHtml += `
      <tr class="font-bold">
        <td>Total ${title}</td>
        <td class="text-right">${formatCurrency(Math.abs(sectionTotal))}</td>
      </tr>
    `;

    return { html: sectionHtml, total: sectionTotal };
  };

  const revenue = renderSection('REVENUE', data.revenue || []);
  html += revenue.html;
  html += '<tr><td colspan="2" style="height: 16px;"></td></tr>';

  const expenses = renderSection('EXPENSES', data.expenses || []);
  html += expenses.html;

  const surplus = (data.totalRevenue || 0) - (data.totalExpenses || 0);
  html += `
    <tr class="total-row">
      <td>NET SURPLUS / (DEFICIT)</td>
      <td class="text-right ${surplus >= 0 ? 'positive' : 'negative'}">${formatCurrency(surplus)}</td>
    </tr>
  `;

  html += '</tbody></table>';
  return html;
}

export function generateCashflowHTML(data: any): string {
  let html = '<table><tbody>';

  const sections = [
    { title: 'Operating Activities', key: 'operating' },
    { title: 'Investing Activities', key: 'investing' },
    { title: 'Financing Activities', key: 'financing' },
  ];

  for (const section of sections) {
    const items = data[section.key] || [];
    html += `<tr class="section-header"><td colspan="2">${section.title}</td></tr>`;

    for (const item of items) {
      html += `
        <tr>
          <td class="indent">${item.description}</td>
          <td class="text-right">${formatCurrency(item.amount)}</td>
        </tr>
      `;
    }

    html += `
      <tr class="font-bold">
        <td>Net Cash from ${section.title}</td>
        <td class="text-right">${formatCurrency(data[`${section.key}Total`] || 0)}</td>
      </tr>
      <tr><td colspan="2" style="height: 12px;"></td></tr>
    `;
  }

  html += `
    <tr class="total-row">
      <td>Net Change in Cash</td>
      <td class="text-right">${formatCurrency(data.netChange || 0)}</td>
    </tr>
    <tr>
      <td>Opening Cash Balance</td>
      <td class="text-right">${formatCurrency(data.openingBalance || 0)}</td>
    </tr>
    <tr class="total-row">
      <td>Closing Cash Balance</td>
      <td class="text-right">${formatCurrency(data.closingBalance || 0)}</td>
    </tr>
  `;

  html += '</tbody></table>';
  return html;
}

export function generateAgeingHTML(data: any, type: 'AR' | 'AP'): string {
  const entityLabel = type === 'AR' ? 'Student' : 'Supplier';

  let html = `
    <table>
      <thead>
        <tr>
          <th>${entityLabel}</th>
          <th class="text-right">Current</th>
          <th class="text-right">1-30 Days</th>
          <th class="text-right">31-60 Days</th>
          <th class="text-right">61-90 Days</th>
          <th class="text-right">90+ Days</th>
          <th class="text-right">Total</th>
        </tr>
      </thead>
      <tbody>
  `;

  for (const row of data.rows || []) {
    html += `
      <tr>
        <td>${row.name}</td>
        <td class="text-right">${formatCurrency(row.current)}</td>
        <td class="text-right">${formatCurrency(row.days1to30)}</td>
        <td class="text-right">${formatCurrency(row.days31to60)}</td>
        <td class="text-right">${formatCurrency(row.days61to90)}</td>
        <td class="text-right">${formatCurrency(row.days90plus)}</td>
        <td class="text-right font-bold">${formatCurrency(row.total)}</td>
      </tr>
    `;
  }

  html += `
      <tr class="total-row">
        <td>TOTALS</td>
        <td class="text-right">${formatCurrency(data.totals?.current)}</td>
        <td class="text-right">${formatCurrency(data.totals?.days1to30)}</td>
        <td class="text-right">${formatCurrency(data.totals?.days31to60)}</td>
        <td class="text-right">${formatCurrency(data.totals?.days61to90)}</td>
        <td class="text-right">${formatCurrency(data.totals?.days90plus)}</td>
        <td class="text-right">${formatCurrency(data.totals?.total)}</td>
      </tr>
    </tbody>
    </table>
  `;

  return html;
}

export async function closeBrowser() {
  if (browserInstance) {
    await browserInstance.close();
    browserInstance = null;
  }
}
