import { NextRequest, NextResponse } from "next/server";
import { withAuth } from "@/lib/middleware-utils";
import prisma from "@/lib/db";
import { jsPDF } from "jspdf";

function money(value: any) {
  const n = Number(value || 0);
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export async function GET(
  req: NextRequest,
  props: { params: Promise<{ id: string }> }
) {
  const params = await props.params;
  return withAuth(req, async (authReq) => {
    const invoice = await prisma.aRInvoice.findUnique({
      where: { id: params.id },
      include: {
        student: true,
        voucher: true,
        lines: true,
      },
    });

    if (!invoice) {
      return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
    }

    if (invoice.organisationId !== authReq.user.organisationId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const org = await prisma.organisation.findUnique({ where: { id: invoice.organisationId } });

    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const width = doc.internal.pageSize.getWidth();
    let y = 15;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(org?.name || "School Invoice", width / 2, y, { align: "center" });
    y += 8;

    doc.setFontSize(14);
    doc.text("Student Invoice", width / 2, y, { align: "center" });
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const left = 15;
    const right = 120;

    doc.text(`Invoice No: ${invoice.voucher?.number || invoice.id}`, left, y);
    doc.text(`Date: ${invoice.voucher?.date ? new Date(invoice.voucher.date).toLocaleDateString("en-GB") : "-"}`, right, y);
    y += 6;
    doc.text(`Student: ${invoice.student?.firstName || ""} ${invoice.student?.lastName || ""}`.trim(), left, y);
    doc.text(`Student No: ${invoice.student?.studentNumber || "-"}`, right, y);
    y += 6;
    doc.text(`Grade/Form: ${invoice.student?.grade || "-"}`, left, y);
    doc.text(`Class: ${invoice.student?.class || "-"}`, right, y);
    y += 6;
    doc.text(`Term: ${invoice.term || "-"}`, left, y);
    doc.text(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString("en-GB") : "-"}`, right, y);
    y += 10;

    doc.setFont("helvetica", "bold");
    doc.text("Description", 15, y);
    doc.text("Qty", 120, y);
    doc.text("Unit Price", 145, y);
    doc.text("Amount", 180, y, { align: "right" });
    y += 3;
    doc.line(15, y, 195, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    for (const line of invoice.lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(String(line.description || ""), 15, y);
      doc.text(String(line.quantity || ""), 120, y);
      doc.text(money(line.unitPrice), 145, y);
      doc.text(money(line.amount), 180, y, { align: "right" });
      y += 7;
    }

    y += 3;
    doc.line(120, y, 195, y);
    y += 7;
    doc.setFont("helvetica", "bold");
    doc.text(`Total (${invoice.currencyCode}):`, 145, y);
    doc.text(money(invoice.amount), 180, y, { align: "right" });
    y += 6;
    doc.text(`Balance:`, 145, y);
    doc.text(money(invoice.balance), 180, y, { align: "right" });
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Status: ${invoice.voucher?.status || invoice.status || "-"}`, 15, y);
    y += 6;
    doc.text("Generated by IPSAS Accounting System", 15, y);

    const pdf = Buffer.from(doc.output("arraybuffer"));
    return new NextResponse(pdf, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="invoice-${invoice.voucher?.number || invoice.id}.pdf"`,
      },
    });
  }, ["ADMIN", "CLERK", "BURSAR"]);
}
